import { ReduxStore } from "@/front/app/providers"
import "@/front/app/globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ReduxStore>
        <body>{children}</body>
      </ReduxStore>
    </html>
  )
}
